// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtNrKtKFFx_2S1d45svJmnxtnDYt64ejY',
    appId: '1:249442742487:web:dbd03c6a8d34073fcec092',
    messagingSenderId: '249442742487',
    projectId: 'orient-eb724',
    authDomain: 'orient-eb724.firebaseapp.com',
    storageBucket: 'orient-eb724.firebasestorage.app',
    measurementId: 'G-2JJCLKVCS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQkgb_zpsNwpPo-eW5J-uxAuFQsa7RBd4',
    appId: '1:249442742487:android:aca8990889d100cecec092',
    messagingSenderId: '249442742487',
    projectId: 'orient-eb724',
    storageBucket: 'orient-eb724.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmMxxUJaSXhF3sHk8UUyhWAt9CNogu8GM',
    appId: '1:249442742487:ios:c1ff621296ac8c3ecec092',
    messagingSenderId: '249442742487',
    projectId: 'orient-eb724',
    storageBucket: 'orient-eb724.firebasestorage.app',
    androidClientId: '249442742487-6p3so8j1qubrcqffr2b46osd7lt0tqoa.apps.googleusercontent.com',
    iosClientId: '249442742487-lhvic9ub3o84vjthiftoragjmjan8q08.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmMxxUJaSXhF3sHk8UUyhWAt9CNogu8GM',
    appId: '1:249442742487:ios:c1ff621296ac8c3ecec092',
    messagingSenderId: '249442742487',
    projectId: 'orient-eb724',
    storageBucket: 'orient-eb724.firebasestorage.app',
    androidClientId: '249442742487-6p3so8j1qubrcqffr2b46osd7lt0tqoa.apps.googleusercontent.com',
    iosClientId: '249442742487-lhvic9ub3o84vjthiftoragjmjan8q08.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtNrKtKFFx_2S1d45svJmnxtnDYt64ejY',
    appId: '1:249442742487:web:33ac80c3cd4babe0cec092',
    messagingSenderId: '249442742487',
    projectId: 'orient-eb724',
    authDomain: 'orient-eb724.firebaseapp.com',
    storageBucket: 'orient-eb724.firebasestorage.app',
    measurementId: 'G-4S6E2Z4H13',
  );
}
